AWSTemplateFormatVersion: "2010-09-09"

# ------------------------------------------------------------#
# README
# ------------------------------------------------------------#

# ------------------------------------------------------------#
# Template Description
# ------------------------------------------------------------#
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Environment Variable Configs"
        Parameters:
          - EnvConfig
      - Label:
          default: "Project prefix"
        Parameters:
          - PJPrefix
      - Label:
          default: "Computing Environment configs"
        Parameters:
          - ComputeResourceType
      - Label:
          default: "Computing Environment configs"
        Parameters:
          - JobDefinitionType
          - LinuxPlatformVersion

    ParameterLabels:
      ComputeResourceType:
        default: "Computing Environment resource types"
      JobDefinitionType:
        default: "Multi-node parallel job or single node"
      LinuxPlatformVersion:
        default: "Linux platform version"


# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  # NOTE: 環境変数を変更するだけで、別々の環境のリソースを作成できます。
  EnvConfig:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Default: "dev"
  PJPrefix:
    Type: String
    Default: "pjPrefix"
  # コンピューティング環境
  ComputeResourceType:
    Type: String
    Default: "FARGATE"
    AllowedValues:
      - EC2
      - SPOT
      - FARGATE
      - FARGATE_SPOT
  # ジョブ定義
  JobDefinitionType:
    Type: String
    Default: "container"
    AllowedValues:
      - container
      - multinode
  LinuxPlatformVersion:
    Type: String
    Default: "1.4.0"
  ImageTag:
    Type: String
    Default: "latest"
  CpuPlatfromVersion:
    Type: String
    Default: "ARM64"

# ------------------------------------------------------------#
# Input Mappings
# ------------------------------------------------------------#

Mappings:
  # TODO: xxxxx へ追記
  EnvMap:
    dev:
      SecretsManagerArn: "arn:aws:secretsmanager:ap-northeast-1:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    stg:
      SecretsManagerArn: "arn:aws:secretsmanager:ap-northeast-1:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    prod:
      SecretsManagerArn: "arn:aws:secretsmanager:ap-northeast-1:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"


Resources:
  # ------------------------------------------------------------#
  # ComputeEnvironment
  # ------------------------------------------------------------#
  # コンピューティング環境
  ComputeEnv:
    Type: "AWS::Batch::ComputeEnvironment"
    Properties:
      ComputeEnvironmentName: !Sub "${EnvConfig}-${PJPrefix}-compute-env"
      Type: "MANAGED"
      State: "ENABLED"
      ServiceRole: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/batch.amazonaws.com/AWSServiceRoleForBatch"
      ComputeResources:
        Type: !Ref ComputeResourceType
        MaxvCpus: 256
        Subnets:
          - {
              "Fn::ImportValue": !Sub "${EnvConfig}-${PJPrefix}-subnet-1-a-private",
            }
          - {
              "Fn::ImportValue": !Sub "${EnvConfig}-${PJPrefix}-subnet-3-c-private",
            }
        SecurityGroupIds:
          - {
              "Fn::ImportValue": !Sub "${EnvConfig}-${PJPrefix}-batch-sg",
            }

  # ------------------------------------------------------------#
  # JobQueue
  # ------------------------------------------------------------#
  # ジョブキュー
  JobQueue:
    Type: "AWS::Batch::JobQueue"
    Properties:
      ComputeEnvironmentOrder:
        - ComputeEnvironment: !Ref ComputeEnv
          Order: 1
      Priority: 0
      JobQueueName: !Sub "${EnvConfig}-${PJPrefix}-job-que"


  # ------------------------------------------------------------#
  # JobDefinition
  # ------------------------------------------------------------#
  JobDefinition:
    Type: "AWS::Batch::JobDefinition"
    Properties:
      # NOTE: バッチ名（batch-name）を記載
      JobDefinitionName: !Sub "${EnvConfig}-${PJPrefix}-job-definition-batch-name"
      Type: !Ref JobDefinitionType
      Parameters: {}
      Timeout:
        AttemptDurationSeconds: 3600
      PlatformCapabilities:
        - FARGATE
      ContainerProperties:
        Secrets: 
          # Secrets Manager
          - 
            Name: "TEST_1"
            ValueFrom: !Sub
              - "${SecretsManagerArnPerEnv}:TEST_1::"
              - SecretsManagerArnPerEnv: !FindInMap [EnvMap, !Ref EnvConfig, SecretsManagerArn]
          - 
            Name: "TEST_2"
            ValueFrom: !Sub
              - "${SecretsManagerArnPerEnv}:TEST_1::"
              - SecretsManagerArnPerEnv: !FindInMap [EnvMap, !Ref EnvConfig, SecretsManagerArn]
          - 
            Name: "TEST_3"
            ValueFrom: !Sub
              - "${SecretsManagerArnPerEnv}:TEST_1::"
              - SecretsManagerArnPerEnv: !FindInMap [EnvMap, !Ref EnvConfig, SecretsManagerArn]

          # System Manager
          -
            Name: "TZ"
            # NOTE: app_nameを記載
            ValueFrom: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${EnvConfig}/app_name/tz"
        # NOTE: ECR名（batch-name）を記載
        Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EnvConfig}-${PJPrefix}-batch-name:${ImageTag}"
        JobRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${EnvConfig}-${PJPrefix}-batch-job-role"
        ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${EnvConfig}-${PJPrefix}-batch-job-execution-role"
        LogConfiguration:
          LogDriver: "awslogs"
          Options:
            # NOTE: バッチ名（batch-name）を記載
            awslogs-group: !Sub "/batch/job/${EnvConfig}-${PJPrefix}-job-batch-name"
            awslogs-region: !Ref AWS::Region
            awslogs-create-group: "true"
            awslogs-stream-prefix: !Ref ImageTag
        ReadonlyRootFilesystem: true
        ResourceRequirements:
          - Type: MEMORY
            Value: 8192
          - Type: VCPU
            Value: 2.0
        EphemeralStorage:
          SizeInGiB: 21
        FargatePlatformConfiguration:
          PlatformVersion: !Ref LinuxPlatformVersion
        RuntimePlatform:
          OperatingSystemFamily: "LINUX"
          CpuArchitecture: !Ref CpuPlatfromVersion
