AWSTemplateFormatVersion: "2010-09-09"
Transform: Count
# ------------------------------------------------------------#
# README
# ------------------------------------------------------------#

# ------------------------------------------------------------#
# Template Description
# ------------------------------------------------------------#
Description: "s"
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Environment Variable Configs"
        Parameters:
          - EnvConfig
      - Label:
          default: "Project prefix"
        Parameters:
          - PJPrefix

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  # NOTE: 環境変数を変更するだけで、別々の環境のリソースを作成できます。
  EnvConfig:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Default: "dev"
  PJPrefix:
    Type: String
    Default: "pjPrefix"
  # NOTE: AWS Batch一覧
  BatchList:
    Type: CommaDelimitedList
    Default: "
      test1,
      test2,
      test3
      "

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "aws/batch/${EnvConfig}-${PJPrefix}-job-%s"
      RetentionInDays: 30
    Count: !Ref BatchList

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
# Outputs:
#   LogGroup:
#     Value: !GetAtt LogGroup.Arn
#     Export:
#       Name: !Sub "${EnvConfig}-${PJPrefix}-log-group-arn"

