AWSTemplateFormatVersion: "2010-09-09"
# ------------------------------------------------------------#
# README
# ------------------------------------------------------------#
# - AWSアカウントで一番最初にECSを作成する場合、テンプレートにて作成すると、サービスリンクがない為、リソースの作成に失敗してしまう。
#   サービスリンクロールを作成する or （自動的にサービスリンクロールが作成されるため）ECSクラスターを一度マネージメントコンソール上で作成してから本テンプレートをデプロイしてください。

# ------------------------------------------------------------#
# Template Description
# ------------------------------------------------------------#
Description: ""
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Environment Variable configs"
        Parameters:
          - EnvConfig
      - Label:
          default: "Project prefix"
        Parameters:
          - PJPrefix
      - Label:
          default: "ECS Service configuration"
        Parameters:
          - ContainerPort
          - TaskDefName
          - TaskDefRevision
      - Label:
          default: "ECS Service common configuration"
        Parameters:
          - LinuxPlatformVersion
          - DeployControllerType

    ParameterLabels:
      ContainerPort:
        default: "Container port"
      TaskDefName:
        default: "Task definition name"
      TaskDefRevision:
        default: "Revision of task definition"
      LinuxPlatformVersion:
        default: "Linux platform version of Fargate task infrastructure"
      DeployControllerType:
        default: "Types of ECS deployment methods"

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  # NOTE: 環境変数を変更するだけで、別々の環境のリソースを作成できます。
  EnvConfig:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Default: "dev"
  PJPrefix:
    Type: String
    Default: "pjPrefix"
  # Service
  ContainerPort:
    Type: Number
    Default: 3000
  TaskDefName:
    Type: String
    Default: "dev-pjprefix-task-definition"
    AllowedValues:
      - "dev-pjprefix-task-definition"
      - "stg-pjprefix-task-definition"
      - "prod-pjprefix-task-definition"
    Description: "Task definition name"
  TaskDefRevision:
    Type: String
    Default: "1"
    Description: "Revision of task definitions"
  # Service（共通パラメーター）
  LinuxPlatformVersion:
    Type: String
    Default: "1.4.0"
  DeployControllerType:
    Type: String
    Default: "CODE_DEPLOY"
    AllowedValues:
      - ECS
      - CODE_DEPLOY
      - EXTERNAL

# ------------------------------------------------------------#
# Conditions
# ------------------------------------------------------------#
Conditions:
  IsDev: !Or
    - !Equals [!Ref EnvConfig, "dev"]


Resources:
  # ------------------------------------------------------------#
  # Cluster
  # ------------------------------------------------------------#
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Sub "${EnvConfig}-${PJPrefix}-ecs-cluster"
      ClusterSettings:
        - Name: "containerInsights"
          Value: !If [IsDev, "disabled", "enabled"]
      CapacityProviders:
        - "FARGATE"
        - "FARGATE_SPOT"

  # ------------------------------------------------------------#
  # Service
  # ------------------------------------------------------------#
  # サービス
  Service:
    Type: "AWS::ECS::Service"
    Properties:
      ServiceName: !Sub "${EnvConfig}-${PJPrefix}-ecs-service-test"
      Cluster: !Ref ECSCluster
      LoadBalancers:
        - TargetGroupArn: { "Fn::ImportValue": !Sub "${EnvConfig}-${PJPrefix}-target-group-test-blue" }
          ContainerName: !Sub "${EnvConfig}-${PJPrefix}-app-test"
          ContainerPort: !Ref ContainerPort
      DesiredCount: !If [IsDev, 1, 2]
      PlatformVersion: !Ref LinuxPlatformVersion
      TaskDefinition: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${TaskDefName}:${TaskDefRevision}"
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: "DISABLED"
          SecurityGroups:
            - { "Fn::ImportValue": !Sub "${EnvConfig}-${PJPrefix}-ecs-sg" }
          Subnets:
            - { "Fn::ImportValue": !Sub "${EnvConfig}-${PJPrefix}-subnet-1-a-private" }
            - { "Fn::ImportValue": !Sub "${EnvConfig}-${PJPrefix}-subnet-3-c-private" }
      HealthCheckGracePeriodSeconds: 0
      SchedulingStrategy: "REPLICA"
      DeploymentController:
        Type: !Ref DeployControllerType
      CapacityProviderStrategy:
        - CapacityProvider: "FARGATE"
          Weight: 1
          Base: 0

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
  # ECSクラスター
  ECSCluster:
    Value: !Ref ECSCluster
    Export:
      Name: !Sub "${EnvConfig}-${PJPrefix}-ecs-cluster"

  # ECSクラスター名
  ECSClusterName:
    Value: !Sub "${EnvConfig}-${PJPrefix}-ecs-cluster"
    Export:
      Name: !Sub "${EnvConfig}-${PJPrefix}-ecs-cluster-name"

  # ECSサービス
  Service:
    Value: !Ref Service
    Export:
      Name: !Sub "${EnvConfig}-${PJPrefix}-ecs-service-test"

  # ECSサービス名
  ServiceName:
    Value: !Sub "${EnvConfig}-${PJPrefix}-ecs-service-test"
    Export:
      Name: !Sub "${EnvConfig}-${PJPrefix}-ecs-service-test-name"
