AWSTemplateFormatVersion: "2010-09-09"
Transform: Count
# ------------------------------------------------------------#
# README
# ------------------------------------------------------------#

# ------------------------------------------------------------#
# Template Description
# ------------------------------------------------------------#
Description: ""
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Environment Variable Configs"
        Parameters:
          - EnvConfig
      - Label:
          default: "Project prefix"
        Parameters:
          - PJPrefix

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  # NOTE: 環境変数を変更するだけで、別々の環境のリソースを作成できます。
  EnvConfig:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Default: "stg"
  PJPrefix:
    Type: String
    Default: "pjPrefix"
  AppDomain:
    Type: String
    Default: "pjPrefix"

Resources:
  # ------------------------------------------------------------#
  # Trace Group （アプリ - 全API）
  # ------------------------------------------------------------#
  BackendAPIResponseTimeGroup:
    Type: "AWS::XRay::Group"
    Properties:
      GroupName: "api-responsetime-2.0sec"
      # NOTE: APIの応答速度が2.0秒を超える場合、このフィルターにて検知される。
      FilterExpression: !Sub 'http.url BEGINSWITH "${AppDomain}" AND responsetime > 2.0'
      InsightsConfiguration:
        InsightsEnabled: false
        NotificationsEnabled: false
        
  # ---------------------------------------------------------------------------------------#
  # Trace Group （AWS Batch） タイムアウト時間：3600秒 / アラーム：2880秒（タイムアウト時間の80%）
  # ---------------------------------------------------------------------------------------#
  BatchAppResponseTime2880Group:
    Type: "AWS::XRay::Group"
    Properties:
      GroupName: "batch-app-responsetime-2880sec"
      # NOTE: "service(id(name: トレース名))" とする。トレース名はX-Rayのトレース一覧画面で確認可能
      FilterExpression: !Sub
        '
          service(id(name: "${EnvConfig}-${PJPrefix}-job-test1")) {responsetime > 2880} OR
          service(id(name: "${EnvConfig}-${PJPrefix}-job-test2")) {responsetime > 2880} OR
          service(id(name: "${EnvConfig}-${PJPrefix}-job-test3")) {responsetime > 2880}
        '
      InsightsConfiguration:
        InsightsEnabled: false
        NotificationsEnabled: false
